# permissions for end users to view pulsarmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pulsarmanager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pulsar-operator
    app.kubernetes.io/part-of: pulsar-operator
    app.kubernetes.io/managed-by: kustomize
  name: pulsarmanager-viewer-role
rules:
- apiGroups:
  - pulsar.monime.sl
  resources:
  - pulsarmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pulsar.monime.sl
  resources:
  - pulsarmanagers/status
  verbs:
  - get
