# permissions for end users to edit pulsarclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarcluster-editor-role
rules:
  - apiGroups:
      - pulsar.monime.sl
    resources:
      - pulsarclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.monime.sl
    resources:
      - pulsarclusters/status
    verbs:
      - get
