# permissions for end users to edit pulsarclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pulsarcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pulsar-operator
    app.kubernetes.io/part-of: pulsar-operator
    app.kubernetes.io/managed-by: kustomize
  name: pulsarcluster-editor-role
rules:
- apiGroups:
  - pulsar.monime.sl
  resources:
  - pulsarclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pulsar.monime.sl
  resources:
  - pulsarclusters/status
  verbs:
  - get
