# permissions for end users to view pulsarproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarproxy-viewer-role
rules:
  - apiGroups:
      - pulsar.monime.sl
    resources:
      - pulsarproxies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - pulsar.monime.sl
    resources:
      - pulsarproxies/status
    verbs:
      - get
