# permissions for end users to view pulsarmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarmanager-viewer-role
rules:
  - apiGroups:
      - pulsar.monime.sl
    resources:
      - pulsarmanagers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - pulsar.monime.sl
    resources:
      - pulsarmanagers/status
    verbs:
      - get
